[package]
name = "vulkano_example"
version = "0.1.0"
edition = "2021"

[dependencies]
vulkano = { version = "0.35", features = ["build-from-source"] }
vulkano-shaders = "0.35"
vulkano-taskgraph = "0.35"
vulkano-util = "0.35"