[package]
name = "app2_wgpu_project"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.28"
env_logger = "0.10"
log = "0.4"
wgpu = "0.13"
pollster = "0.3"  # For blocking on wgpu futures in async contexts
noise = "0.7"      # For Perlin noise generation