services:
  jproj_vulkan:
    command: ["sh", "-c", "cargo run --release"]
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RUST_LOG=debug
    stdin_open: true
    tty: true
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]