services:
  jproj_vulkan:
    build: .
    volumes:
      - .:/app
    environment:
      - RUST_LOG=debug
    stdin_open: true
    tty: true
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]